name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Integrate vcpkg
      run: vcpkg integrate install

    # Source - https://stackoverflow.com/a/79852893
    # Posted by Amit, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-04-16, License - CC BY-SA 4.0
    - name: Install Visual Studio Build Tools
      shell: pwsh
      run: |
        Write-Host "Installing VS 2026 Build Tools..."
        choco install visualstudio2026buildtools `
          --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --quiet" `
          -y --ignore-package-exit-codes=3010
        Write-Host "VS 2026 Build Tools installation completed" 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    # Source - https://stackoverflow.com/a/79852893
    # Posted by Amit, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-04-16, License - CC BY-SA 4.0
    - name: Build Solution
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\Common7\Tools\VsDevCmd.bat"
        msbuild /m ^
          /p:Configuration=Release ^
          /p:Platform=x86 ^
          statsgate.sln

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: nightly-binaries
        path: |
          Release/*.exe
          Release/*.dll
